### ISSUE TITLE
possible to place items inside of eachother

### ISSUE THREAD

**Issue by Bamper-sand** [camerongillette/factorio_blueprint_editor#20]
if you take an item larger than one tile (oil refinery for example) only the top left tile has collision and it is possible to place items inside of each other
![image](https://user-images.githubusercontent.com/33892064/33116416-890c887c-cf5c-11e7-95b2-8f1f95374ac9.png)

**Comment by Armienn** [comment]
This is fixed in the current version: https://camerongillette.github.io/factorio_blueprint_editor/
Thanks for the report, though.
