### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jrp55** [camerongillette/factorio_blueprint_editor#26]
It's a 'boring' thing, but I'd say that it's a good idea to choose and add a license to this project. I recommend http://choosealicense.com/ as an information source.

**Comment by palexcast** [comment]
MIT?

**Comment by jrp55** [comment]
I think that this is a thing for @elxeno (or possibly @camerongillette ) to decide upon.

**Comment by elxeno** [comment]
MIT sounds good
