### ISSUE TITLE
Enable Travis-CI for this repo

### ISSUE THREAD

**Issue by Zeragamba** [camerongillette/factorio_blueprint_editor#35]
Travis-CI needs to be enabled by the repo owner

@camerongillette can enable it from here: https://travis-ci.org/camerongillette/factorio_blueprint_editor

**Comment by Zeragamba** [comment]
Might also be a good idea to mark the master branch as a protected branch. This would force any changes to the master branch to be done through Pull Requests, and waits for Travis-CI to mark the changes as good.

**Comment by camerongillette** [comment]
@SpyMaster356 Master is now protected. I don't see a Travis-CL in github users, do you know his exact username?

**Comment by Zeragamba** [comment]
You'll need to enable the service through the link I posted above.

**Comment by camerongillette** [comment]
@SpyMaster356 Derp, I read that way too literally. It's complete.
