### ISSUE TITLE
Underground Belt Rotation

### ISSUE THREAD

**Issue by StripedMonkey** [camerongillette/factorio_blueprint_editor#39]
This sorta has to do with #8, Currently we have two icons for input/output of each belt. However they are all facing the same direction so having properly connected belts will make it look something like
![this](https://user-images.githubusercontent.com/8009284/33354466-1007351a-d481-11e7-9347-9b8015f673e2.png) 
It would be good if at the very least had the  belts mirrored when rotated so that they go the same direction without being upside down.
Would it be possible to take the sprite sheet, cut out the needed ones and cycle through the individual rotations instead of having a single texture?

**Comment by camerongillette** [comment]
The code I have in #38 should accommodate once it gets merged in.

**Comment by camerongillette** [comment]
Also the underground pipe suffers from the same issue.

**Comment by camerongillette** [comment]
@StripedMonkey  Completed.
