### ISSUE TITLE
Create responsive version of layout for mobile and tablet

### ISSUE THREAD

**Issue by camerongillette** [camerongillette/factorio_blueprint_editor#7]

**Comment by palexcast** [comment]
If it's okay I'll take a look at rewriting some of the css using grid, then making it responsive should be quite easy, if I don't do it straight away :) Thoughts?

https://css-tricks.com/snippets/css/complete-guide-grid/

**Comment by Zeragamba** [comment]
Are we going to support touch interfaces? right now the only way to remove items on touch is to clear the whole grid as you don't have a "right click" on touch.

**Comment by palexcast** [comment]
What about a toggle (erase/insert) button on touch interfaces?  A responsive site is nice anyway, for example when having two windows side-by-side.
